In [2]:
# Install missing packages to kernel.

! pip install pandas
! pip install scikit-learn
! pip install numpy

In [3]:
# Import packages.

import pandas as pd 
import numpy as np
import scipy.sparse as sp
pd.options.display.max_colwidth = None
pd.set_option('display.max_rows', 10)
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import normalize
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity

# CSDS-435: Project #2
# Adam Brennan and Charlie Song

## Helper Functions...

In [4]:
def get_cnn_health_tweets_dataframe():
    # read in the cnnhealth.txt file using utf-8 encoding
    with open('cnnhealth.txt', 'r', encoding='utf-8') as cnn_health_tweets_dataset:
        # initialize empty list to store tweets
        tweets = []

        # for each row in the dataset, skip the first two columns and append the tweet to the tweets list
        for row in cnn_health_tweets_dataset:
            columns = row.strip().split('|')
            tweet = '|'.join(columns[2:])
            tweets.append([tweet])

    # convert list of tweets to pandas DataFrame
    df = pd.DataFrame(tweets, columns=['tweet'])
    
    # return the resulting pandas DataFrame
    return df

In [5]:
def get_bag_of_words_matrix(tweets_list):
    # initialize CountVectorizer opbject 
    vectorizer = CountVectorizer()

    # build bag of words matrix from tweets list
    bag_of_words_matrix = vectorizer.fit_transform(tweets_list)
    
    return bag_of_words_matrix

In [6]:
def get_bag_of_words_dataframe(tweets_list):
    # initialize CountVectorizer opbject 
    vectorizer = CountVectorizer()

    # build bag of words matrix from tweets list
    bag_of_words_matrix = vectorizer.fit_transform(tweets_list)

    # convert bag of words matrix to a pandas DataFrame
    bag_of_words_df = pd.DataFrame(bag_of_words_matrix.toarray(), columns = vectorizer.get_feature_names_out())
    
    return bag_of_words_df

In [7]:
def get_tweet(tweets_df, tweet_index):
    # return the tweet at the specified index in string form
    return str(tweets_df.iloc[tweet_index])

In [8]:
def get_num_total_tokens(tweets_list):
    num_total_tokens = 0

    for tweet in tweets_list:
        num_total_tokens += len(tweet)

    return num_total_tokens

In [9]:
def get_tweets_summary_dataframe(tweets_list):
    num_tweets = len(tweets_list)
    num_total_tokens = get_num_total_tokens(tweets_list)
    num_unique_tokens = get_bag_of_words_dataframe(tweets_list).shape[1]
    num_avg_tokens_per_tweet = num_total_tokens / num_tweets

    data = [[num_tweets, num_total_tokens, num_unique_tokens, num_avg_tokens_per_tweet, 'CNN Health Tweets']]

    columns = ['# Tweets', '# Total Tokens', '# Unique Tokens', 'Avg. Tokens Per Tweet', 'Description']

    tweets_summary_dataframe = pd.DataFrame(data, columns=columns)
    
    return tweets_summary_dataframe

In [10]:
def get_euclidean_distance(bag_of_words_matrix):
    bag_of_words_matrix_ed = euclidean_distances(bag_of_words_matrix)

    np.savetxt("euclidean_distance.txt", bag_of_words_matrix_ed, delimiter=',', fmt='%.2f')

    return bag_of_words_matrix_ed

In [11]:
def get_cosine_similarity(bag_of_words_matrix):
    bag_of_words_matrix_cs = cosine_similarity(bag_of_words_matrix)

    np.savetxt("cosine_similarity.txt", bag_of_words_matrix_cs, delimiter=',', fmt='%.2f')

    return bag_of_words_matrix_cs

### Reading in the "cnnhealth.txt" file...

In [12]:
# get pandas DataFrame
tweets_df = get_cnn_health_tweets_dataframe()

# display DataFrame
tweets_df

tweet
0                         An abundance of online info can turn us into e-hypochondriacs. Or, worse, lead us to neglect getting the care we need http://cnn.it/1L1t1Fv
1     A plant-based diet that incorporates fish may be the key to preventing colorectal cancers: http://cnn.it/1xdpsjT http://pbs.twimg.com/media/CAARHEGWEAAJGz6.jpg
2                            It doesn't take much to damage your hearing at a sports bar or nightclub. That's why a billion people are at risk. http://cnn.it/1BOphBk
3                         RT @CNN: Forever young? Discover this island’s secrets to longevity on #TheWonderList w/ @BillWeirCNN  http://cnn.it/1GNdmqc https://t.co/…
4                         RT @CNN: Is post-traumatic stress disorder in your genes? A simple blood test may one day help tell you http://cnn.it/1xls8w5 http://t.co/…
...                                                                                                                                                               ...
4056                                                           RT @EverydayHealth: Want killer abs? @JillianMichaels shows you how get them: http://at.cnn.com/ubAkAN
4057                                                                    Medicare at stake -- @sanjayguptaCNN talks about politicians' plans http://at.cnn.com/7nLSOm7
4058                                                                                          Ann Romney talks about her experience with MS http://at.cnn.com/khb6keC
4059                                                                                         Make sure your first marathon isn't your last! http://at.cnn.com/liehiPl
4060                                                                                                        Robin Roberts' cancer diagnosis http://at.cnn.com/XNq3fhk

[4061 rows x 1 columns]

### Get tweet as list...

In [13]:
# get list of tweets
tweets_list = tweets_df['tweet'].tolist()

### Get the "bag of words" pandas DataFrame using the previously generated tweets pandas DataFrame...

In [14]:
# generate "bag of words" pandas DataFrame
bag_of_words_dataframe = get_bag_of_words_dataframe(tweets_list)

# display "bag of words" pandas DataFrame
bag_of_words_dataframe

000  008relo  00fvvdw  00igyua  01  01tdt1o  02  03  04  05  ...  \
0       0        0        0        0   0        0   0   0   0   0  ...   
1       0        0        0        0   0        0   0   0   0   0  ...   
2       0        0        0        0   0        0   0   0   0   0  ...   
3       0        0        0        0   0        0   0   0   0   0  ...   
4       0        0        0        0   0        0   0   0   0   0  ...   
...   ...      ...      ...      ...  ..      ...  ..  ..  ..  ..  ...   
4056    0        0        0        0   0        0   0   0   0   0  ...   
4057    0        0        0        0   0        0   0   0   0   0  ...   
4058    0        0        0        0   0        0   0   0   0   0  ...   
4059    0        0        0        0   0        0   0   0   0   0  ...   
4060    0        0        0        0   0        0   0   0   0   0  ...   

      zwwtu7  zxodiqo  zy53fec  zy7u11  zyam2xi  zyl  zyt5bpe  zzetat  \
0          0        0        0       0        0    0        0       0   
1          0        0        0       0        0    0        0       0   
2          0        0        0       0        0    0        0       0   
3          0        0        0       0        0    0        0       0   
4          0        0        0       0        0    0        0       0   
...      ...      ...      ...     ...      ...  ...      ...     ...   
4056       0        0        0       0        0    0        0       0   
4057       0        0        0       0        0    0        0       0   
4058       0        0        0       0        0    0        0       0   
4059       0        0        0       0        0    0        0       0   
4060       0        0        0       0        0    0        0       0   

      zzgrrgf  zzzzz  
0           0      0  
1           0      0  
2           0      0  
3           0      0  
4           0      0  
...       ...    ...  
4056        0      0  
4057        0      0  
4058        0      0  
4059        0      0  
4060        0      0  

[4061 rows x 11264 columns]

### Get the tweets summary DataFrame...

In [15]:
# generate "bag of words" pandas DataFrame
tweets_summary_dataframe = get_tweets_summary_dataframe(tweets_list)

tweets_summary_dataframe

# Tweets  # Total Tokens  # Unique Tokens  Avg. Tokens Per Tweet  \
0      4061          441036            11264             108.602807   

         Description  
0  CNN Health Tweets

### Distance measure #1: Eucliean distance

In [16]:
bag_of_words_matrix = get_bag_of_words_matrix(tweets_list)

bag_of_words_matrix_ed = get_euclidean_distance(bag_of_words_matrix)

bag_of_words_matrix_ed

array([[0.        , 6.4807407 , 6.55743852, ..., 6.        , 6.164414  ,
        5.65685425],
       [6.4807407 , 0.        , 6.40312424, ..., 5.65685425, 5.83095189,
        5.29150262],
       [6.55743852, 6.40312424, 0.        , ..., 5.74456265, 5.56776436,
        5.38516481],
       ...,
       [6.        , 5.65685425, 5.74456265, ..., 0.        , 4.47213595,
        3.74165739],
       [6.164414  , 5.83095189, 5.56776436, ..., 4.47213595, 0.        ,
        4.        ],
       [5.65685425, 5.29150262, 5.38516481, ..., 3.74165739, 4.        ,
        0.        ]])

### Distance measure #2: Cosine similarity

In [17]:
bag_of_words_matrix = get_bag_of_words_matrix(tweets_list)

bag_of_words_matrix_cs = get_cosine_similarity(bag_of_words_matrix)

bag_of_words_matrix_cs

array([[1.        , 0.22222222, 0.21821789, ..., 0.1067521 , 0.0993808 ,
        0.12830006],
       [0.22222222, 1.        , 0.25458754, ..., 0.21350421, 0.1987616 ,
        0.25660012],
       [0.21821789, 0.25458754, 1.        , ..., 0.20965697, 0.29277002,
        0.25197632],
       ...,
       [0.1067521 , 0.21350421, 0.20965697, ..., 1.        , 0.28644595,
        0.36980013],
       [0.0993808 , 0.1987616 , 0.29277002, ..., 0.28644595, 1.        ,
        0.34426519],
       [0.12830006, 0.25660012, 0.25197632, ..., 0.36980013, 0.34426519,
        1.        ]])

In [18]:
pd.set_option('display.max_rows', None)


### Clustering using KMeans...

#### First cluster with euclidean distance as the distance measure...

In [19]:
bow = get_bag_of_words_matrix(tweets_list)

kmeans = KMeans(n_clusters = 20, random_state = 0)
kmeans.fit(bow)

labels = kmeans.labels_
labels

c:\Users\charl\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


array([14, 16, 17, ...,  2, 17, 18])

In [20]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 1]

tweets  \
999          Starting soon: Allergies getting you down? Join our #CNNAllergies Twitter chat at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1003       TODAY: Join our #CNNAllergies Twitter chat at 1:30pm EST with @AllergyReliefNY and ask all of your allergy questions http://on.fb.me/1k9W1v8   
1005                 TODAY: Allergies getting you down? Join our #CNNAllergies Twitter chat at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1009       Questions about #allergies? Ask us using hashtag #CNNAllergies. Chat is TOMORROW at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1011                       Allergies getting you down? Join our #CNNAllergies chat TOMORROW at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1013                                                   Join our #CNNAllergies chat TOMORROW at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1016                 Learn about #allergies tomorrow! Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1023          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1026                     Allergies getting you down? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1027                     Allergies getting you down? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1029          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1033       What do you want to know about #allergies? Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1035       What do you want to know about #allergies? Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1037          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1041                     Allergies getting you down? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1044          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1064                                           @MelEdits Thanks for those #CNNAllergies Qs! We hope you'll join us for the chat on 4/23 at 1:30 p.m EST   
1073       What do you want to know about #allergies? Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1696  Join us &amp; @namicommunicate @DrashmanCNN @KellyWallaceTV tmw for a chat on raising kids w/ mental illness: http://on.fb.me/1d5gkEa #CNNParents   

      label  
999       1  
1003      1  
1005      1  
1009      1  
1011      1  
1013      1  
1016      1  
1023      1  
1026      1  
1027      1  
1029      1  
1033      1  
1035      1  
1037      1  
1041      1  
1044      1  
1064      1  
1073      1  
1696      1

#### First cluster with cosine similarity as the distance measure...

In [21]:
bow = get_bag_of_words_matrix(tweets_list)
normalized_bow = normalize(bow, norm='l2', axis=1)

kmeans = KMeans(n_clusters = 30, random_state = 0)
kmeans.fit(normalized_bow)

labels = kmeans.labels_
labels

c:\Users\charl\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


array([21,  6,  2, ..., 15, 28, 15])

In [22]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 0]

tweets  \
1907                                                         . @Schwarzenegger trained 1 hr/day to be in shape for @EscapePlanMovie. His tips for working out on the road http://www.cnn.com/2013/10/18/health/arnold-schwarzenegger-travel-workout/index.html   
1936                                                                                                        Mentally ill #Latinos struggle to get help http://www.cnn.com/2013/10/09/health/latino-mental-health-disparities/index.html #LATISM @UN @WHO #WMHD   
1945                                                                    Fat-burning supplement pulled from shelves after it's linked to liver failure, acute hepatitis http://www.cnn.com/2013/10/09/health/oxyelite-pro-liver-damage/index.html @HIgov_Health   
1946                                                                                                                #Latinos struggle to find help for #mental #health issues http://www.cnn.com/2013/10/09/health/latino-mental-health-disparities/index.html   
1969                                                              Were you or your child supposed to start a clinical trial that may be delayed b/c of the #shutdown? Let us know http://www.cnn.com/2013/10/01/health/shutdown-nih-clinical-trials/index.html   
1975                                                                                                                                                                  Why #beer is good for your health http://www.cnn.com/2013/09/30/health/beer-good-health/   
1976                                                                                     It's news Homer Simpson will love: Beer, it's good for you. The health benefits of a good cold one:  http://www.cnn.com/2013/09/30/health/beer-good-health/?hpt=he_t3   
1977                                                  An ireporter lost 158 pounds in part by leaving a photographic reminder of just how heavy he was everywhere he looked http://www.cnn.com/2013/09/30/health/irpt-weight-loss-trotter/index.html?hpt=he_c1   
1978                                                                                                                                      Check out these 15 superfoods for fall! http://www.cnn.com/2013/09/27/health/gallery/best-fall-superfoods/index.html   
1979                                                              Hip hop health, a fun &amp; effective health program that helps kids lose weight &amp; helped one kid save his grandma's life http://www.cnn.com/2013/09/27/health/hip-hop-health/index.html   
1980                                                                                      #Obamacare 101: if you plan to shop in the marketplaces here's everything you need to know http://www.cnn.com/2013/09/26/health/obamacare-open-enrollment/index.html   
1981                                                                   It's open enrollment time. These are health insurance terms most people don't know. What you don't know can cost you http://www.cnn.com/2013/09/26/health/obamacare-glossary/index.html   
1983                                                                                                           5 questions you should be sure to ask before going under the knife: http://www.cnn.com/2013/09/25/health/surgery-questions/index.html?hpt=he_c1   
1984                                                                                                                           Interactive map of health care options under #Obamacare: http://www.cnn.com/interactive/2013/09/health/map-obamacare/index.html   
1986                                                                                                                   Drinking really does reduce stress... kind of. http://www.cnn.com/2013/09/24/health/drinking-reduces-stress-upwave/index.html?hpt=he_c1   
1988                                                                                           Regina Lopez went from 22

### Clustering using Hierarhical Clustering...

#### First cluster with euclidean distance as the distance measure...

In [23]:
bow = get_bag_of_words_matrix(tweets_list)
normalized_bow = normalize(bow, norm='l2', axis=1)
dense_bow = bow.todense()
bow_array = np.array(dense_bow)

hierarchica_clustering = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')
hierarchica_clustering.fit(bow_array)

labels = hierarchica_clustering.labels_
labels

c:\Users\charl\anaconda3\Lib\site-packages\sklearn\cluster\_agglomerative.py:1005: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(


array([1, 3, 4, ..., 1, 1, 1], dtype=int64)

In [24]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 4]

tweets  \
2                                                                         It doesn't take much to damage your hearing at a sports bar or nightclub. That's why a billion people are at risk. http://cnn.it/1BOphBk   
3                                                                      RT @CNN: Forever young? Discover this island’s secrets to longevity on #TheWonderList w/ @BillWeirCNN  http://cnn.it/1GNdmqc https://t.co/…   
4                                                                      RT @CNN: Is post-traumatic stress disorder in your genes? A simple blood test may one day help tell you http://cnn.it/1xls8w5 http://t.co/…   
7                                                                      RT @CNNOpinion: Women can defeat #Alzheimers, says @mariashriver. #WipeOutAlz challenge will make it happen. http://cnn.it/1AklXJQ http://…   
9                                                                                                CDC: Misuse of garments may have led to release of bioterror bacteria at Tulane monkey lab. http://cnn.it/18HDKDg   
17                                                                                                                  RT @cnnbrk: U.S. Ebola patient headed to National Institutes of Health. http://cnn.it/1BxKgIa.   
22                                                                                               Kids = constant ear infections. Save yourself a trip to the ER w/ this: http://cnn.it/1xg6t8x #cnninstantstartups   
26                                                                                                         Could a simple blood test someday tell if you're genetically predisposed to PTSD? http://cnn.it/1Mvai0w   
27                                                                 RT @CNN: Explore the secrets of Ikaria on #TheWonderList with @BillWeirCNN Sun at 10pET/PT. http://cnn.it/1EfbKSL https://vine.co/v/O9nAHUHOnK2   
28                                                                     Ear trouble? Save yourself a trip to the ER. One startup has created an iPhone attachment to diagnose ear infections. http://cnn.it/1GIzkux   
31                                                                                                        A Tulane researcher has been exposed to deadly bioterror bacteria at a monkey lab. http://cnn.it/1AhvHnW   
32                                                                                                                 Be careful when diagnosing your ailments online and avoid these mistakes. http://cnn.it/1L1t1Fv   
34                                                                                             His 3 simple secrets to a long &amp; happy life? #TheWonderList w/ @BillWeirCNN Sun. 10p @CNN http://cnn.it/1HEjTRR   
42                                                                     RT @CNN: Trauma and grief don't always fit neatly into five textbook stages, @drsanjaygupta says. http://cnn.it/1MrpygJ http://t.co/KKmg3X…   
45                                                                     RT @drsanjaygupta: what @milesobrien teaches us about loss, and being found: http://cnn.it/1ERcoXS @CNN @AC360 @andersoncooper http://t.co…   
46                                             Stages of grief: What @milesobrien teaches us about loss and being found, from @drsanjaygupta. http://cnn.it/1wVVNRW http://pbs.twimg.com/media/B_vZ0-wWAAAkK5r.jpg   
47                                                                                                                                 RT @CNN: How did toddler survive car crash in Utah river? http://cnn.it/1C0MVe1   
53                                                                                         College kids make robotic arms for children without real ones http://cnn.it/1DTjXJI #3DPrinted via @cnnireport @dsashin   
55                                   RT @kellywallacetv: Q's about women's mental health &amp; meds. Join @CNN NOW w psychiatrist @Bellevu

#### First cluster with cosine similarity as the distance measure...

In [25]:
bow = get_bag_of_words_matrix(tweets_list)
normalized_bow = normalize(bow, norm='l2', axis=1)
dense_bow = normalized_bow.todense()
bow_array = np.array(dense_bow)

hierarchica_clustering = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')
hierarchica_clustering.fit(bow_array)

labels = hierarchica_clustering.labels_
labels

c:\Users\charl\anaconda3\Lib\site-packages\sklearn\cluster\_agglomerative.py:1005: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(


array([4, 2, 1, ..., 1, 1, 1], dtype=int64)

In [26]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 3]

tweets  \
114                                                                                           Whitney Houston's daughter still on ventilator http://www.cnn.com/2015/02/02/entertainment/whitney-houston-daughter-hospitalized/index.html   
117                                                                                                                         Fit Nation is back: Meet the new team http://www.cnn.com/2015/01/28/health/feat-fit-nation-is-back/index.html   
120                                               Details emerge about Joan Rivers death after lawsuit filed from @jechristensen http://www.cnn.com/2015/01/26/health/joan-rivers-lawsuit/ http://pbs.twimg.com/media/B8VAgxHCYAETD6L.jpg   
122                     The world is one step closer to having a real weapon to fight Ebola, from @jechristensen http://www.cnn.com/2015/01/23/health/feat-ebola-vaccine-latest/index.html http://pbs.twimg.com/media/B8CvTxaIgAAEvrB.jpg   
128                                                                                   The flu is back at an epidemic level http://www.cnn.com/2015/01/16/health/new-flu-numbers/index.html http://pbs.twimg.com/media/B7gO-9eCMAIEmQ3.jpg   
131                                                                  Heroin deaths are up for a third year in a row http://www.cnn.com/2015/01/14/health/heroin-deaths-increase/index.html http://pbs.twimg.com/media/B7Z0w7sCYAAM-Jq.jpg   
132                                                      What are "natural flavors," really? @AmandaWoerner http://www.cnn.com/2015/01/14/health/feat-natural-flavors-explained/index.html http://pbs.twimg.com/media/B7VZavoIIAAky2s.jpg   
133                    Do any of your resolutions involve eating better?  Here's some easy ways to do just that http://www.cnn.com/2015/01/14/health/feat-healthy-eating-habits/index.html http://pbs.twimg.com/media/B7VRs4CCcAAW-LX.jpg   
145                                               The flu is coming to a state near you (if it isn't there already) http://www.cnn.com/2015/01/05/health/flu-activitity-spreads/index.html http://pbs.twimg.com/media/B6nz0vYCIAAExRX.jpg   
147           Caramel apples thought to be linked to deadly listeria outbreak in 10 states @jechristensen http://www.cnn.com/2014/12/19/health/caramel-apple-listeria/index.html?hpt=he_c2 http://pbs.twimg.com/media/B5Pfk_mIgAAHQBT.jpg   
148       Feeling less than festive this holiday season? Here are a few easy ways to beat holiday blues. http://www.cnn.com/2014/12/19/health/surviving-holiday-blues/index.html?hpt=he_c1 http://pbs.twimg.com/media/B5OrgkOIEAAUaFe.jpg   
149                                                                                  The debilitating outbreak sweeping the Americas http://www.cnn.com/2014/12/17/health/chikungunya-infects-the-americas/index.html?sr=sharebar_twitter   
152                                                                                                                Teens do fewer drugs and drink less. http://www.cnn.com/2014/12/16/health/feat-teen-drug-use-down/index.html?hpt=he_c1   
153                                                      Here's the health reasons why it is good that Angelina Jolie stayed home from her movie premiere http://www.cnn.com/2014/12/15/health/chicken-pox-explained/index.html?hpt=he_c2   
154                                  Just in time for the holidays: Here are 5 easy ways to "fat proof" your home http://www.cnn.com/2014/12/12/health/fat-proof-home/index.html?hpt=he_c1 http://pbs.twimg.com/media/B46Si_ACAAAn7Pq.jpg   
155                                                                                                                     How a hockey player put pain on ice http://www.cnn.com/2014/12/11/health/human-factor-hockey/index.html?hpt=he_c1   
161                    Have you checked this list to be sure the items on your child's Christmas list are ok? http://www.cnn.com/2014/12/04/health/child-toy-injuries/index.html?hpt=he_c1 http://pbs.

### Clustering using DBSCAN...

#### First cluster with euclidean distance as the distance measure...

In [27]:
bow = get_bag_of_words_matrix(tweets_list)

cluster = DBSCAN(eps=3, min_samples=2).fit(bow)

labels = cluster.labels_
labels

array([-1, -1, -1, ..., -1, -1, 10], dtype=int64)

In [28]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 1]

tweets  \
197                                                                   #StrokeChat #WorldStrokeDay http://pbs.twimg.com/media/B1IVu2QCAAAM8or.jpg   
203   Are you at risk? Join us for a #WorldStrokeDay #StrokeChat w/ @American_Stroke at 1 p.m. ET http://pbs.twimg.com/media/B1G_rDaCAAANet9.jpg   
204                    Join us for a #WorldStrokeDay #StrokeChat w/ @American_Stroke at 1 p.m. ET http://pbs.twimg.com/media/B1G_aLSCAAAeyBU.jpg   
777                                       RT @DarianMurray: @cnnhealth oatmeal. Raisins, walnuts. http://pbs.twimg.com/media/BpNETvqIQAAWzsn.jpg   
778                              RT @DDworkouts: @cnnhealth granola, yogurt, strawberries. Fancy. http://pbs.twimg.com/media/BpNRZhfCYAAc1xT.jpg   
1175                                           RT @UMN_Health: @cnnhealth @WilliamCNN We do, too! http://pbs.twimg.com/media/BjqbzykCEAAU7Sc.jpg   
1176                                           RT @MMGHealth: @cnnhealth @WilliamCNN We hear you! http://pbs.twimg.com/media/BjqOwO2CAAA4Mtx.jpg   
1185                                                           Mmmm! RT @AtarheHoover: @cnnhealth http://pbs.twimg.com/media/BjkodIgCYAEghBa.jpg   
1186                                                                   RT @apelsinkaX: @cnnhealth http://pbs.twimg.com/media/BjkiAskIYAA4r7G.jpg   
2851                                               RT @Taversha: @cnnhealth A cup ring of pollen! http://pbs.twimg.com/media/BHlpN0cCQAE8Ez2.jpg   

      label  
197       1  
203       1  
204       1  
777       1  
778       1  
1175      1  
1176      1  
1185      1  
1186      1  
2851      1

#### First cluster with cosine similarity as the distance measure...

In [29]:
bow = get_bag_of_words_matrix(tweets_list)
normalized_bow = normalize(bow, norm='l2', axis=1)

cluster = DBSCAN(eps=3, min_samples=2).fit(normalized_bow)

labels = cluster.labels_
labels

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 1]

Empty DataFrame
Columns: [tweets, label]
Index: []

### Clustering using EM Clustering...

#### First cluster with euclidean distance as the distance measure...

In [35]:
bow = get_bag_of_words_matrix(tweets_list)
normalized_bow = normalize(bow, norm='l2', axis=1)
dense_bow = bow.todense()
bow_array = np.asarray(dense_bow)

cluster = GaussianMixture(n_components=3)
cluster.fit(bow_array)

labels = cluster.predict(bow_array)
labels

array([1, 0, 1, ..., 2, 2, 2], dtype=int64)

In [36]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 1]

tweets  \
0                                                                            An abundance of online info can turn us into e-hypochondriacs. Or, worse, lead us to neglect getting the care we need http://cnn.it/1L1t1Fv   
2                                                                               It doesn't take much to damage your hearing at a sports bar or nightclub. That's why a billion people are at risk. http://cnn.it/1BOphBk   
3                                                                            RT @CNN: Forever young? Discover this island’s secrets to longevity on #TheWonderList w/ @BillWeirCNN  http://cnn.it/1GNdmqc https://t.co/…   
9                                                                                                      CDC: Misuse of garments may have led to release of bioterror bacteria at Tulane monkey lab. http://cnn.it/18HDKDg   
12                                                                           RT @CNN: A plant-based diet that incorporates fish may be the key to preventing colorectal cancers: http://cnn.it/1x1ffMU http://t.co/OIu6…   
17                                                                                                                        RT @cnnbrk: U.S. Ebola patient headed to National Institutes of Health. http://cnn.it/1BxKgIa.   
22                                                                                                     Kids = constant ear infections. Save yourself a trip to the ER w/ this: http://cnn.it/1xg6t8x #cnninstantstartups   
26                                                                                                               Could a simple blood test someday tell if you're genetically predisposed to PTSD? http://cnn.it/1Mvai0w   
28                                                                           Ear trouble? Save yourself a trip to the ER. One startup has created an iPhone attachment to diagnose ear infections. http://cnn.it/1GIzkux   
31                                                                                                              A Tulane researcher has been exposed to deadly bioterror bacteria at a monkey lab. http://cnn.it/1AhvHnW   
34                                                                                                   His 3 simple secrets to a long &amp; happy life? #TheWonderList w/ @BillWeirCNN Sun. 10p @CNN http://cnn.it/1HEjTRR   
40                                                                          RT @milesobrien: Thanks to @drsanjaygupta @roniselig @susanchun1 @tinkertime @calebhell @AC360 for such a powerful film. I hope this teache…   
43                                                                        RT @CNNMoney: Would you trust this to measure your blood sugar? http://cnnmon.ie/18xMYBU @AmDiabetesAssn cc @HeatherKelly25 http://t.co/cehJY…   
51                                                                                                                                    What you need to know about daylight savings and your health http://cnn.it/1BbQIEt   
60                                                                                                RT @roniselig: Huge Congrats to @elizcohencnn with @JBONIFIELDCNN winning #Gracie 2015 award-Orig Online series #Ebola   
69                                                                             CNN's medical unit Sr. EP @roniselig is featured in the NYT for her dedication to running, even in the bitter cold http://nyti.ms/188LcHf   
74                                                                                                                             The latest Obamacare challenge: What you need to know @CNNPolitics  http://cnn.it/1DaEkBz   
77                                                                           RT @drsanjaygupta: exposing kids to #peanuts early in life may actually keep them from developing an #allergy -- http://cnn.it/17uAFWC htt…   
78                            

#### First cluster with cosine similarity as the distance measure...

In [38]:
bow = get_bag_of_words_matrix(tweets_list)
normalized_bow = normalize(bow, norm='l2', axis=1)
dense_bow = normalized_bow.todense()
bow_array = np.asarray(dense_bow)

cluster = GaussianMixture(n_components=3)
cluster.fit(bow_array)

labels = cluster.predict(bow_array)
labels

array([2, 2, 1, ..., 0, 0, 0], dtype=int64)

In [39]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 2]

tweets  \
0                                                                                                                  An abundance of online info can turn us into e-hypochondriacs. Or, worse, lead us to neglect getting the care we need http://cnn.it/1L1t1Fv   
1                                                                                              A plant-based diet that incorporates fish may be the key to preventing colorectal cancers: http://cnn.it/1xdpsjT http://pbs.twimg.com/media/CAARHEGWEAAJGz6.jpg   
3                                                                                                                  RT @CNN: Forever young? Discover this island’s secrets to longevity on #TheWonderList w/ @BillWeirCNN  http://cnn.it/1GNdmqc https://t.co/…   
4                                                                                                                  RT @CNN: Is post-traumatic stress disorder in your genes? A simple blood test may one day help tell you http://cnn.it/1xls8w5 http://t.co/…   
5                                                                                                     Maysoon Zayid, a touring standup comic with Cerebral Palsy, has a message to share. http://cnn.it/1GNiH0L http://pbs.twimg.com/media/B__ubV_UQAAUNOO.jpg   
6                                                                                                                                How women can wipe out Alzheimer's, from @mariashriver.  http://cnn.it/1AklXJQ http://pbs.twimg.com/media/B__sQMiUUAAGMre.jpg   
7                                                                                                                  RT @CNNOpinion: Women can defeat #Alzheimers, says @mariashriver. #WipeOutAlz challenge will make it happen. http://cnn.it/1AklXJQ http://…   
8                                                                                                                                              Is it time to raise the legal smoking age? http://cnn.it/1GNhBC8 http://pbs.twimg.com/media/B__rgYfUwAALomW.jpg   
9                                                                                                                                            CDC: Misuse of garments may have led to release of bioterror bacteria at Tulane monkey lab. http://cnn.it/18HDKDg   
10                                                                                          Losing a brain tumor, gaining perspective: CNN's Jessica Moskowitz's #FirstPerson experience. http://cnn.it/1EhlrjJ http://pbs.twimg.com/media/B_-tiaAUgAArA_6.jpg   
11                                                                                                               You may be your germs: Microbe genes slipped into human DNA, study says. http://cnn.it/1AukT5d http://pbs.twimg.com/media/B_-rUkAUUAAXUyO.jpg   
12                                                                                                                 RT @CNN: A plant-based diet that incorporates fish may be the key to preventing colorectal cancers: http://cnn.it/1x1ffMU http://t.co/OIu6…   
13                                                                                                       #FitNation: Finding the right life balance between family, work and getting fit. http://cnn.it/18GEfgH http://pbs.twimg.com/media/B_-p3vAU0AAKb-F.jpg   
14                                                                                                                Robert Downey Jr. presents a child with his own 'Iron Man' robotic arm. http://cnn.it/1Gxrm3R http://pbs.twimg.com/media/B_-o-RyUIAAHCKo.jpg   
15                                                                                                       RT @cnntech: Tim Cook tried to give Steve Jobs his liver http://cnnmon.ie/1Eh7Usn via @DavidGoldmanCNN http://pbs.twimg.com/media/B_-SdBDVAAAOtY7.jpg   
16                                                                                                 RT @drsanjaygupta: wh