In [136]:
# Install missing packages to kernel.

! pip install pandas
! pip install scikit-learn
! pip install numpy


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [215]:
# Import packages.

import pandas as pd 
import numpy as np
pd.options.display.max_colwidth = None
pd.set_option('display.max_rows', 10)
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import normalize
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity

# CSDS-435: Project #2
# Adam Brennan and Charlie Song

## Helper Functions...

In [216]:
def get_cnn_health_tweets_dataframe():
    # read in the cnnhealth.txt file using utf-8 encoding
    with open('cnnhealth.txt', 'r', encoding='utf-8') as cnn_health_tweets_dataset:
        # initialize empty list to store tweets
        tweets = []

        # for each row in the dataset, skip the first two columns and append the tweet to the tweets list
        for row in cnn_health_tweets_dataset:
            columns = row.strip().split('|')
            tweet = '|'.join(columns[2:])
            tweets.append([tweet])

    # convert list of tweets to pandas DataFrame
    df = pd.DataFrame(tweets, columns=['tweet'])
    
    # return the resulting pandas DataFrame
    return df

In [217]:
def get_bag_of_words_matrix(tweets_list):
    # initialize CountVectorizer opbject 
    vectorizer = CountVectorizer()

    # build bag of words matrix from tweets list
    bag_of_words_matrix = vectorizer.fit_transform(tweets_list)
    
    return bag_of_words_matrix

In [218]:
def get_bag_of_words_dataframe(tweets_list):
    # initialize CountVectorizer opbject 
    vectorizer = CountVectorizer()

    # build bag of words matrix from tweets list
    bag_of_words_matrix = vectorizer.fit_transform(tweets_list)

    # convert bag of words matrix to a pandas DataFrame
    bag_of_words_df = pd.DataFrame(bag_of_words_matrix.toarray(), columns = vectorizer.get_feature_names_out())
    
    return bag_of_words_df

In [219]:
def get_tweet(tweets_df, tweet_index):
    # return the tweet at the specified index in string form
    return str(tweets_df.iloc[tweet_index])

In [220]:
def get_num_total_tokens(tweets_list):
    num_total_tokens = 0

    for tweet in tweets_list:
        num_total_tokens += len(tweet)

    return num_total_tokens

In [221]:
def get_tweets_summary_dataframe(tweets_list):
    num_tweets = len(tweets_list)
    num_total_tokens = get_num_total_tokens(tweets_list)
    num_unique_tokens = get_bag_of_words_dataframe(tweets_list).shape[1]
    num_avg_tokens_per_tweet = num_total_tokens / num_tweets

    data = [[num_tweets, num_total_tokens, num_unique_tokens, num_avg_tokens_per_tweet, 'CNN Health Tweets']]

    columns = ['# Tweets', '# Total Tokens', '# Unique Tokens', 'Avg. Tokens Per Tweet', 'Description']

    tweets_summary_dataframe = pd.DataFrame(data, columns=columns)
    
    return tweets_summary_dataframe

In [222]:
def get_euclidean_distance(bag_of_words_matrix):
    bag_of_words_matrix_ed = euclidean_distances(bag_of_words_matrix)

    np.savetxt("euclidean_distance.txt", bag_of_words_matrix_ed, delimiter=',', fmt='%.2f')

    return bag_of_words_matrix_ed

In [223]:
def get_cosine_similarity(bag_of_words_matrix):
    bag_of_words_matrix_cs = cosine_similarity(bag_of_words_matrix)

    np.savetxt("cosine_similarity.txt", bag_of_words_matrix_cs, delimiter=',', fmt='%.2f')

    return bag_of_words_matrix_cs

### Reading in the "cnnhealth.txt" file...

In [224]:
# get pandas DataFrame
tweets_df = get_cnn_health_tweets_dataframe()

# display DataFrame
tweets_df

tweet
0                         An abundance of online info can turn us into e-hypochondriacs. Or, worse, lead us to neglect getting the care we need http://cnn.it/1L1t1Fv
1     A plant-based diet that incorporates fish may be the key to preventing colorectal cancers: http://cnn.it/1xdpsjT http://pbs.twimg.com/media/CAARHEGWEAAJGz6.jpg
2                            It doesn't take much to damage your hearing at a sports bar or nightclub. That's why a billion people are at risk. http://cnn.it/1BOphBk
3                         RT @CNN: Forever young? Discover this island’s secrets to longevity on #TheWonderList w/ @BillWeirCNN  http://cnn.it/1GNdmqc https://t.co/…
4                         RT @CNN: Is post-traumatic stress disorder in your genes? A simple blood test may one day help tell you http://cnn.it/1xls8w5 http://t.co/…
...                                                                                                                                                               ...
4056                                                           RT @EverydayHealth: Want killer abs? @JillianMichaels shows you how get them: http://at.cnn.com/ubAkAN
4057                                                                    Medicare at stake -- @sanjayguptaCNN talks about politicians' plans http://at.cnn.com/7nLSOm7
4058                                                                                          Ann Romney talks about her experience with MS http://at.cnn.com/khb6keC
4059                                                                                         Make sure your first marathon isn't your last! http://at.cnn.com/liehiPl
4060                                                                                                        Robin Roberts' cancer diagnosis http://at.cnn.com/XNq3fhk

[4061 rows x 1 columns]

### Get tweet as list...

In [127]:
# get list of tweets
tweets_list = tweets_df['tweet'].tolist()

### Get the "bag of words" pandas DataFrame using the previously generated tweets pandas DataFrame...

In [130]:
# generate "bag of words" pandas DataFrame
bag_of_words_dataframe = get_bag_of_words_dataframe(tweets_list)

# display "bag of words" pandas DataFrame
bag_of_words_dataframe

000  008relo  00fvvdw  00igyua  01  01tdt1o  02  03  04  05  ...  \
0       0        0        0        0   0        0   0   0   0   0  ...   
1       0        0        0        0   0        0   0   0   0   0  ...   
2       0        0        0        0   0        0   0   0   0   0  ...   
3       0        0        0        0   0        0   0   0   0   0  ...   
4       0        0        0        0   0        0   0   0   0   0  ...   
...   ...      ...      ...      ...  ..      ...  ..  ..  ..  ..  ...   
4056    0        0        0        0   0        0   0   0   0   0  ...   
4057    0        0        0        0   0        0   0   0   0   0  ...   
4058    0        0        0        0   0        0   0   0   0   0  ...   
4059    0        0        0        0   0        0   0   0   0   0  ...   
4060    0        0        0        0   0        0   0   0   0   0  ...   

      zwwtu7  zxodiqo  zy53fec  zy7u11  zyam2xi  zyl  zyt5bpe  zzetat  \
0          0        0        0       0        0    0        0       0   
1          0        0        0       0        0    0        0       0   
2          0        0        0       0        0    0        0       0   
3          0        0        0       0        0    0        0       0   
4          0        0        0       0        0    0        0       0   
...      ...      ...      ...     ...      ...  ...      ...     ...   
4056       0        0        0       0        0    0        0       0   
4057       0        0        0       0        0    0        0       0   
4058       0        0        0       0        0    0        0       0   
4059       0        0        0       0        0    0        0       0   
4060       0        0        0       0        0    0        0       0   

      zzgrrgf  zzzzz  
0           0      0  
1           0      0  
2           0      0  
3           0      0  
4           0      0  
...       ...    ...  
4056        0      0  
4057        0      0  
4058        0      0  
4059        0      0  
4060        0      0  

[4061 rows x 11264 columns]

### Get the tweets summary DataFrame...

In [225]:
# generate "bag of words" pandas DataFrame
tweets_summary_dataframe = get_tweets_summary_dataframe(tweets_list)

tweets_summary_dataframe

# Tweets  # Total Tokens  # Unique Tokens  Avg. Tokens Per Tweet  \
0      4061          441036            11264             108.602807   

         Description  
0  CNN Health Tweets

### Distance measure #1: Eucliean distance

In [226]:
bag_of_words_matrix = get_bag_of_words_matrix(tweets_list)

bag_of_words_matrix_ed = get_euclidean_distance(bag_of_words_matrix)

bag_of_words_matrix_ed

array([[0.        , 6.4807407 , 6.55743852, ..., 6.        , 6.164414  ,
        5.65685425],
       [6.4807407 , 0.        , 6.40312424, ..., 5.65685425, 5.83095189,
        5.29150262],
       [6.55743852, 6.40312424, 0.        , ..., 5.74456265, 5.56776436,
        5.38516481],
       ...,
       [6.        , 5.65685425, 5.74456265, ..., 0.        , 4.47213595,
        3.74165739],
       [6.164414  , 5.83095189, 5.56776436, ..., 4.47213595, 0.        ,
        4.        ],
       [5.65685425, 5.29150262, 5.38516481, ..., 3.74165739, 4.        ,
        0.        ]])

### Distance measure #2: Cosine similarity

In [227]:
bag_of_words_matrix = get_bag_of_words_matrix(tweets_list)

bag_of_words_matrix_cs = get_cosine_similarity(bag_of_words_matrix)

bag_of_words_matrix_cs

array([[1.        , 0.22222222, 0.21821789, ..., 0.1067521 , 0.0993808 ,
        0.12830006],
       [0.22222222, 1.        , 0.25458754, ..., 0.21350421, 0.1987616 ,
        0.25660012],
       [0.21821789, 0.25458754, 1.        , ..., 0.20965697, 0.29277002,
        0.25197632],
       ...,
       [0.1067521 , 0.21350421, 0.20965697, ..., 1.        , 0.28644595,
        0.36980013],
       [0.0993808 , 0.1987616 , 0.29277002, ..., 0.28644595, 1.        ,
        0.34426519],
       [0.12830006, 0.25660012, 0.25197632, ..., 0.36980013, 0.34426519,
        1.        ]])

In [228]:
pd.set_option('display.max_rows', None)


### Clustering using KMeans...

#### First cluster with euclidean distance as the distance measure...

In [231]:
bow = get_bag_of_words_matrix(tweets_list)

kmeans = KMeans(n_clusters = 20, random_state = 0)
kmeans.fit(bow)

labels = kmeans.labels_
labels

array([14, 16, 17, ...,  2, 17, 18], dtype=int32)

In [235]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 1]

tweets  \
999          Starting soon: Allergies getting you down? Join our #CNNAllergies Twitter chat at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1003       TODAY: Join our #CNNAllergies Twitter chat at 1:30pm EST with @AllergyReliefNY and ask all of your allergy questions http://on.fb.me/1k9W1v8   
1005                 TODAY: Allergies getting you down? Join our #CNNAllergies Twitter chat at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1009       Questions about #allergies? Ask us using hashtag #CNNAllergies. Chat is TOMORROW at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1011                       Allergies getting you down? Join our #CNNAllergies chat TOMORROW at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1013                                                   Join our #CNNAllergies chat TOMORROW at 1:30pm EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1016                 Learn about #allergies tomorrow! Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1023          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1026                     Allergies getting you down? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1027                     Allergies getting you down? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1029          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1033       What do you want to know about #allergies? Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1035       What do you want to know about #allergies? Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1037          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1041                     Allergies getting you down? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1044          What can you do to get allergy relief? Join our #CNNAllergies chat on 4/23 at 1:30 p.m. EST with @AllergyReliefNY http://on.fb.me/1k9W1v8   
1064                                           @MelEdits Thanks for those #CNNAllergies Qs! We hope you'll join us for the chat on 4/23 at 1:30 p.m EST   
1073       What do you want to know about #allergies? Send us your questions before our #CNNAllergies chat on 4/23 @ 1:30 pm ET http://on.fb.me/1k9W1v8   
1696  Join us &amp; @namicommunicate @DrashmanCNN @KellyWallaceTV tmw for a chat on raising kids w/ mental illness: http://on.fb.me/1d5gkEa #CNNParents   

      label  
999       1  
1003      1  
1005      1  
1009      1  
1011      1  
1013      1  
1016      1  
1023      1  
1026      1  
1027      1  
1029      1  
1033      1  
1035      1  
1037      1  
1041      1  
1044      1  
1064      1  
1073      1  
1696      1

#### First cluster with cosine similarity as the distance measure...

In [240]:
bow = get_bag_of_words_matrix(tweets_list)
normalized_bow = normalize(bow, norm='l2', axis=1)

kmeans = KMeans(n_clusters = 30, random_state = 0)
kmeans.fit(normalized_bow)

labels = kmeans.labels_
labels

array([19,  3,  7, ..., 20, 24, 20], dtype=int32)

In [242]:
df = pd.DataFrame({
    'tweets': tweets_list,
    'label': labels
})

df[df['label'] == 0]

tweets  \
2225               What every new triathlete needs http://at.cnn.com/RVWV4hz Great advice from @chrissiesmiles #triwithme @CNNFitNation   
2228        You're crazy! Overcoming others' negativity in training http://at.cnn.com/Btwtbtg @CNNFitNation @TriHardClevelan #triwithme   
2265               What every new triathlete needs http://at.cnn.com/ZHPbrig Great advice from @chrissiesmiles #triwithme @CNNFitNation   
2421               What I wish I'd known when training for a triathlon http://at.cnn.com/vl5cbhK @TriHardStacy #triwithme @CNNFitNation   
2427   Happy Fitness Friday! Follow the @CNNFitNation team as they train for their first triathlon http://at.cnn.com/XQ55jCK #triwithme   
2544                        Sometimes, you just have to lose control http://at.cnn.com/HzNIiq7 #triwithme @TriHardTabitha @CNNFitNation   
2603                                     Triathlete conquers first time in the ocean http://at.cnn.com/mF7mZM8 #triwithme @CNNFitNation   
2653                            Behind the scenes: Training for a triathlon http://at.cnn.com/GhLeMNn @Spotify @CNNFitNation #triwithme   
2654          Following the @CNNFitNation team? Our fancy new interactive will help you track their progress! http://at.cnn.com/YPjdPgv   
2667  5 rules for new triathletes. @CNNFitNation coach @aprils_awesome shares her inside knowledge http://at.cnn.com/yWScDn8 #triwithme   
2668                                  Our @CNNFitNation team is in Florida this week. Check out these photos! http://at.cnn.com/FUgeVC0   
2679                           Check out this #storify with tweets from our @CNNFitNation team in Florida http://sfy.co/s5yh #triwithme   
2686                                  Our @CNNFitNation team is in Florida this week. Check out these photos! http://at.cnn.com/dfx6iQa   
2706                       3 lessons from a triathlete-to-be http://at.cnn.com/MfnB86w #triwithme #getfit @CNNFitNation @TriHardDouglas   
2838                       Our @CNNFitNation team learned a few valuable lessons in eating healthy http://at.cnn.com/A7aHTcA #triwithme   
3059               . @TriHardStacy overcomes his biggest excuse: 'I am not a runner' http://at.cnn.com/uDY72i0 #triwithme @CNNFitNation   
3198                      So proud! Our @CNNFitNation team kicked off their training by conquering a mountain http://at.cnn.com/YhSQRLE   
3933                               Race day tips for the @CNNFitNation team from Ironman champ @chrissiesmiles http://at.cnn.com/jGtRUb   
3939                                  Bride's vows: 'In fitness and in health' (via @CNNFitNation ) http://at.cnn.com/mUMszX #triwithme   
3942                           Making your health a priority, even on the road http://at.cnn.com/YrJHFy #triwithme (via @CNNFitNation )   

      label  
2225      0  
2228      0  
2265      0  
2421      0  
2427      0  
2544      0  
2603      0  
2653      0  
2654      0  
2667      0  
2668      0  
2679      0  
2686      0  
2706      0  
2838      0  
3059      0  
3198      0  
3933      0  
3939      0  
3942      0

### Clustering using Hierarhical Clustering...

#### First cluster with euclidean distance as the distance measure...

#### First cluster with cosine similarity as the distance measure...

### Clustering using DBSCAN...

#### First cluster with euclidean distance as the distance measure...

#### First cluster with cosine similarity as the distance measure...

### Clustering using EM Clustering...

#### First cluster with euclidean distance as the distance measure...

#### First cluster with cosine similarity as the distance measure...